---
#
# file: set_ios_banner_modt.yml
#
# Stores the Message Of The Day (motd) banner to the device. Due to the fact,
# that the IOS Version is displayed in the banner, this script has to be executed after
# version upgrade
#
# uses template:
#   /templates/{{ ansible_network_os }}/ios_banner_motd.j2"
#
# Incompatibility: C6848er Switch will not provide the serial numbers therefore
#                  the Core Switches are excluded fom playbook
#
- hosts: ios:!ATBRACSC*:!ATKPACSC*
  gather_facts: no
  become: no

  vars:
    dest_filename_part: "_ios_banner"
    dest_filename: "{{ config_dir }}/{{ inventory_hostname }}_{{dest_filename_part}}.{{ ansible_network_os }}"
    template_name: "ios_banner_motd.j2"

  tasks:

    - name: Read the serial numbers
      ios_facts:
      register: facts
      check_mode: no

    - name: Setup Config directory
      block:
        - set_fact:
            config_filename: "{{ config_dir }}/{{ inventory_hostname }}"
            display_core: "{{ '( --- CORE-SWITCH --- )' if is_default_gateway is defined and is_default_gateway == true else '' }}"
        - file:
            path: "{{ config_dir }}"
            state: directory
      delegate_to: localhost
      check_mode: no

    - template:
        src: "{{ template_dir }}/{{ ansible_network_os }}/{{ template_name }}"
        dest: "{{ dest_filename }}"
        lstrip_blocks: true
      delegate_to: localhost
      check_mode: no
      register: motd_res

    - name: Display motd_res
      debug:
        msg: "New or updated: {{ dest_filename }}"
      changed_when: false
      when:
        - motd_res.changed
      check_mode: no
      delegate_to: localhost
      tags: [print_action]

    - name: "Configure banner from: {{ dest_filename }}"
      ios_banner:
        banner:  motd
        text: "{{ lookup('file', dest_filename ) }}"
        state: present
      when:
        - motd_res.changed
      tags: [print_action]
