---
#
# file: hosts.yml
#
# Inventory for production environment
#
all:
  vars:
    is_develop: true
  children:
    # All switches
    switches:

      children:
        ios:
          children:
            ios_planta:
              # All IOS Switches in plant_a
              hosts:
                ROUTER01:
                  ansible_host: 172.23.228.1

                SW001:
                  ansible_host: 172.23.228.51

                SW002:
                  ansible_host: 172.23.228.2

            # ios_dmz:
            #   hosts:
            #     ATBRACSW001:
            #       ansible_host: 192.168.228.10

            #     ATBRACSW051:
            #       ansible_host: 192.168.228.51
